type Query {
  author(id: ID): Author!
  authors: [Author]!
  book(id: ID): Book!
  books: [Book]!
}

type Mutation {
  # addAuthor(name: String, age: Int): Author
  addBook(name: String, genre: String): Book
}

type Author {
  id: ID
  name: String
  age: Int
  books: [Book]!
}

type Book {
  id: ID
  name: String
  genre: String
  author: Author
}
